// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_voltaje.h"
#include "screens/ui_corriente.h"
#include "screens/ui_dashboard.h"
#include "screens/ui_Modo_Diario_24hrs.h"
#include "screens/ui_statsWatts.h"
#include "screens/ui_voltageStats.h"
#include "screens/ui_diagnostic.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_LecturaS);
LV_FONT_DECLARE(ui_font_LecturaS48);
LV_FONT_DECLARE(ui_font_Micro_text);
LV_FONT_DECLARE(ui_font_Secondary_info);
LV_FONT_DECLARE(ui_font_Unidades);
LV_FONT_DECLARE(ui_font_RobotoMono96);
LV_FONT_DECLARE(ui_font_LecturaS);
LV_FONT_DECLARE(ui_font_diagElem);
LV_FONT_DECLARE(ui_font_diagTitle);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
