// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_helpers.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Modo_Diario_24hrs.h"
#include "screens/ui_config.h"
#include "screens/ui_config_brightness.h"
#include "screens/ui_burnout.h"
#include "screens/ui_corriente.h"
#include "screens/ui_dashboard.h"
#include "screens/ui_diagnostic.h"
#include "screens/ui_statsWatts.h"
#include "screens/ui_voltageStats.h"
#include "screens/ui_voltaje.h"


///////////////////// VARIABLES ////////////////////

// EVENTS

extern lv_obj_t *ui____initial_actions0;
extern lv_obj_t * ui_valoresPanel13;
extern lv_obj_t * ui_valoresPanel14;
extern lv_obj_t * ui_PotenciaLabel15;

// FONTS
LV_FONT_DECLARE(ui_font_Qualy12);
LV_FONT_DECLARE(ui_font_Qualy14);
LV_FONT_DECLARE(ui_font_Qualy24);
LV_FONT_DECLARE(ui_font_Qualy28);
LV_FONT_DECLARE(ui_font_Qualy48);
LV_FONT_DECLARE(ui_font_Qualy72);
LV_FONT_DECLARE(ui_font_Qualy96);
LV_FONT_DECLARE(ui_font_Qualy150);
LV_FONT_DECLARE(ui_font_Qualy200);
LV_FONT_DECLARE(ui_font_Qualy114);
LV_FONT_DECLARE(ui_font_Qualy180);
LV_FONT_DECLARE(ui_font_Qualy82);
LV_FONT_DECLARE(ui_font_Qualy90);

// GLOBALS (configuración centralizada)
#include "ui_globals.h"

extern bool is_wifi_enabled;

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_check_voltage_warning(float voltage);
void ui_check_current_warning(float current);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
