// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <stdio.h>
#include <string.h>
#include <time.h>
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"

void voltageStatsChange(lv_event_t *e) {
  _ui_screen_change(&ui_statsWatts, UI_ANIM_SWIPE_UP, UI_ANIM_SWIPE_DURATION,
                    UI_ANIM_SWIPE_DELAY, &ui_statsWatts_screen_init);
}

void statsWattsChange(lv_event_t *e) {
  _ui_screen_change(&ui_voltageStats, UI_ANIM_SWIPE_UP, UI_ANIM_SWIPE_DURATION,
                    UI_ANIM_SWIPE_DELAY, &ui_voltageStats_screen_init);
}

// ================================================================
// CONFIG: Callbacks reales (conectados a hardware vía main.cpp)
// ================================================================

bool is_wifi_enabled = true; // State for UI elements and screen rotation
// Funciones de hardware declaradas en main.cpp con C-linkage
extern void hw_set_brightness(uint8_t val);
extern void hw_wifi_toggle(bool enable);
extern void hw_restart(void);
extern void hw_request_history(const char* start, const char* end);

// false = semanal (últimos ~7 días), true = mensual (últimos ~30 días)
static bool stats_mode_voltage_monthly = false;
static bool stats_mode_watts_monthly = false;

void ui_event_stats_load(lv_event_t *e) {
  lv_obj_t * target = (e != NULL) ? lv_event_get_target(e) : lv_scr_act();
  bool is_monthly = false;

  // Sincronizar UI y obtener el modo correcto según la pantalla
  if (target == ui_voltageStats) {
    if (ui_voltageVal) lv_label_set_text(ui_voltageVal, "...");
    is_monthly = stats_mode_voltage_monthly;
    if (ui_PotenciaLabel17) lv_label_set_text(ui_PotenciaLabel17, is_monthly ? "Registro mensual volts" : "Registro semanal volts");
    if (ui_voltageChart) lv_chart_set_point_count(ui_voltageChart, is_monthly ? 31 : 7);
  } 
  else if (target == ui_statsWatts) {
    if (ui_wattsVal) lv_label_set_text(ui_wattsVal, "...");
    is_monthly = stats_mode_watts_monthly;
    if (ui_PotenciaLabel16) lv_label_set_text(ui_PotenciaLabel16, is_monthly ? "Registro mensual amps" : "Registro semanal amps");
    if (ui_wattsChart) lv_chart_set_point_count(ui_wattsChart, is_monthly ? 31 : 7);
  }

  // Calcular rango de fechas dinámicamente
  time_t now = time(NULL);
  struct tm *local = localtime(&now);
  
  char start_buf[32], end_buf[32];
  
  if (local == NULL || local->tm_year < (2025 - 1900)) {
    // NTP no ha sincronizado aún, usar fallback amplio
    if (is_monthly) {
      hw_request_history("2026-04-01T06:00:00.000Z", "2026-05-01T05:59:59.000Z");
    } else {
      hw_request_history("2026-04-21T06:00:00.000Z", "2026-04-28T05:59:59.000Z");
    }
    return;
  }

  if (is_monthly) {
    // Mensual: del día 1 al último día del mes actual (en UTC, +6h offset)
    snprintf(start_buf, sizeof(start_buf), "%04d-%02d-01T06:00:00.000Z",
             local->tm_year + 1900, local->tm_mon + 1);
    // Primer día del mes siguiente
    int next_mon = local->tm_mon + 2; // tm_mon es 0-based, +1 para humano, +1 para siguiente
    int next_year = local->tm_year + 1900;
    if (next_mon > 12) { next_mon = 1; next_year++; }
    snprintf(end_buf, sizeof(end_buf), "%04d-%02d-01T05:59:59.000Z",
             next_year, next_mon);
  } else {
    // Semanal: calcular el lunes de esta semana
    int wday = local->tm_wday; // 0=Domingo, 1=Lunes...
    int days_since_monday = (wday == 0) ? 6 : (wday - 1);
    
    struct tm monday = *local;
    monday.tm_mday -= days_since_monday;
    monday.tm_hour = 0; monday.tm_min = 0; monday.tm_sec = 0;
    mktime(&monday); // Normaliza (puede cambiar el mes si retrocedemos)
    
    // Lunes 00:00 local = Lunes 06:00 UTC
    snprintf(start_buf, sizeof(start_buf), "%04d-%02d-%02dT06:00:00.000Z",
             monday.tm_year + 1900, monday.tm_mon + 1, monday.tm_mday);
    
    // Domingo siguiente = Monday + 7 días
    struct tm sunday = monday;
    sunday.tm_mday += 7;
    mktime(&sunday);
    snprintf(end_buf, sizeof(end_buf), "%04d-%02d-%02dT05:59:59.000Z",
             sunday.tm_year + 1900, sunday.tm_mon + 1, sunday.tm_mday);
  }

  hw_request_history(start_buf, end_buf);
}

void onBrightnessChange(int32_t value) {
  // Clamp a uint8_t
  uint8_t brightness = (uint8_t)(value > 255 ? 255 : (value < 0 ? 0 : value));
  hw_set_brightness(brightness);
}

void onWifiConfirm(bool enable) { 
  is_wifi_enabled = enable;
  hw_wifi_toggle(enable); 
}
void onRestartConfirm(void) { hw_restart(); }

// Necesitas agregar "extern void hw_turn_off_screen(void);" si lo haces por
// hardware
extern void hw_turn_off_screen(void);

static lv_obj_t *wake_layer = NULL;

extern void hw_restore_brightness(void);

static void wake_layer_cb(lv_event_t *e) {
  if (wake_layer) {
    lv_obj_del(wake_layer);
    wake_layer = NULL;
    hw_restore_brightness();
  }
}

void onTurnOffScreen(void) {
  // Apagar hardware
  hw_turn_off_screen();

  // Crear capa de "despertar" sobre todo
  if (!wake_layer) {
    wake_layer = lv_obj_create(lv_layer_top());
    lv_obj_set_size(wake_layer, lv_pct(100), lv_pct(100));
    lv_obj_set_style_bg_opa(wake_layer, 0, LV_PART_MAIN); // Invisible
    lv_obj_set_style_border_width(wake_layer, 0, LV_PART_MAIN);
    lv_obj_add_flag(wake_layer, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(wake_layer, wake_layer_cb, LV_EVENT_CLICKED, NULL);
  }
}

void ui_event_stats_toggle(lv_obj_t *label, lv_obj_t *chart) {
  if (!label)
    return;
  const char *current_text = lv_label_get_text(label);
  bool turning_monthly = (strstr(current_text, "semanal") != NULL);
  
  if (turning_monthly) {
    if (chart == ui_voltageChart) lv_label_set_text(label, "Registro mensual volts");
    else lv_label_set_text(label, "Registro mensual amps");
  } else {
    if (chart == ui_voltageChart) lv_label_set_text(label, "Registro semanal volts");
    else lv_label_set_text(label, "Registro semanal amps");
  }

  // Guardar flag independiente
  if (chart == ui_voltageChart) stats_mode_voltage_monthly = turning_monthly;
  else if (chart == ui_wattsChart) stats_mode_watts_monthly = turning_monthly;

  // Al cambiar el toggle, pedimos datos con el nuevo rango
  ui_event_stats_load(NULL);
}

// ================================================================
// CHART CALLBACKS: Coloring peligroso + Click para ver valor exacto
// ================================================================

extern lv_coord_t history_voltage[];
extern lv_coord_t history_watts[];
extern char history_timestamps[31][24];
extern int history_count;
extern SemaphoreHandle_t history_mutex;

// Helper para formatear ISO date a texto legible local (-06:00)
// "2026-03-30T00:00:00Z" -> "29 Mar, 18:00"
static void format_timestamp(const char* iso, char* out, size_t out_len) {
    if (strlen(iso) < 16) {
        strlcpy(out, iso, out_len);
        return;
    }

    struct tm t = {0};
    // Format: 2026-03-21T12:00:00Z
    if (iso == NULL || sscanf(iso, "%d-%d-%dT%d:%d", &t.tm_year, &t.tm_mon, &t.tm_mday, &t.tm_hour, &t.tm_min) < 5) {
        strlcpy(out, iso ? iso : "", out_len);
        return;
    }
    
    t.tm_year -= 1900; 
    t.tm_mon -= 1;     
    
    // Ajustar -6 horas (UTC -> Local CST)
    t.tm_hour -= 6;
    
    // mktime normaliza el struct tm (si t.tm_hour se vuelve negativo, resta un día, etc)
    // Usamos mktime y luego gmtime para evitar que el timezone del chip interfiera
    time_t rawtime = mktime(&t);
    struct tm *local = gmtime(&rawtime); 
    
    if (!local) {
        strlcpy(out, iso, out_len);
        return;
    }

    const char* months[] = {"Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"};
    snprintf(out, out_len, "%02d %s, %02d:%02d", 
             local->tm_mday, months[local->tm_mon], 
             local->tm_hour, local->tm_min);
}

// Restaura los labels al promedio global y el título al modo actual
void restore_chart_defaults(lv_obj_t *screen) {
  if (history_mutex == NULL || xSemaphoreTake(history_mutex, pdMS_TO_TICKS(50)) != pdTRUE) return;
  
  if (history_count <= 0) {
      xSemaphoreGive(history_mutex);
      return;
  }
  
  if (screen == ui_voltageStats) {
      if (ui_PotenciaLabel17) lv_label_set_text(ui_PotenciaLabel17, stats_mode_voltage_monthly ? "Registro mensual volts" : "Registro semanal volts");
      int sum = 0;
      for (int i=0; i<history_count; i++) sum += history_voltage[i];
      if (ui_voltageVal) {
          lv_label_set_text_fmt(ui_voltageVal, "%d", sum / history_count);
          lv_obj_set_style_text_color(ui_voltageVal, UI_COLOR_TEXT_LABEL, LV_PART_MAIN | LV_STATE_DEFAULT);
      }
  } else if (screen == ui_statsWatts) {
      if (ui_PotenciaLabel16) lv_label_set_text(ui_PotenciaLabel16, stats_mode_watts_monthly ? "Registro mensual amps" : "Registro semanal amps");
      int sum = 0;
      for (int i=0; i<history_count; i++) sum += history_watts[i];
      if (ui_wattsVal) {
          lv_label_set_text_fmt(ui_wattsVal, "%.2f", (float)sum / history_count / 100.0f);
          lv_obj_set_style_text_color(ui_wattsVal, UI_COLOR_TEXT_LABEL, LV_PART_MAIN | LV_STATE_DEFAULT);
      }
  }
  xSemaphoreGive(history_mutex);
}

// Callback para cuando se toca el fondo de la pantalla (fuera de la gráfica)
void ui_screen_clicked_cb(lv_event_t *e) {
  restore_chart_defaults(lv_event_get_target(e));
}

void ui_chart_draw_event_cb(lv_event_t *e) {
  lv_obj_draw_part_dsc_t *dsc = lv_event_get_draw_part_dsc(e);
  lv_obj_t *chart = lv_event_get_target(e);

  // Intercepción del eje Y para Amperios (dividimos entre 100)
  if (dsc->part == LV_PART_TICKS && dsc->id == LV_CHART_AXIS_PRIMARY_Y && chart == ui_wattsChart) {
    snprintf(dsc->text, dsc->text_length, "%.2f", (float)dsc->value / 100.0f);
    return;
  }

  // Intercepción del eje X (Días)
  if (dsc->part == LV_PART_TICKS && dsc->id == LV_CHART_AXIS_PRIMARY_X) {
    bool is_monthly = (chart == ui_voltageChart) ? stats_mode_voltage_monthly : stats_mode_watts_monthly;
    if (is_monthly) {
      // Mes: leer el día real del timestamp de esa barra
      int idx = dsc->value;
      if (idx >= 0 && idx < 31 && history_timestamps[idx][0] != '\0') {
        int y, m, d;
        if (sscanf(history_timestamps[idx], "%d-%d-%dT", &y, &m, &d) == 3) {
          snprintf(dsc->text, dsc->text_length, "%d", d);
        } else {
          // Fallback: no mostrar nada si el formato falla
          snprintf(dsc->text, dsc->text_length, " ");
        }
      } else {
        // Posición sin datos: no mostrar etiqueta
        snprintf(dsc->text, dsc->text_length, " ");
      }
    } else {
      // Semana: imprimir L, M, M, J, V, S, D
      const char* days[] = {"L", "M", "M", "J", "V", "S", "D"};
      if (dsc->value < 7) {
        snprintf(dsc->text, dsc->text_length, "%s", days[dsc->value]);
      }
    }
    return;
  }

  if (dsc->part != LV_PART_ITEMS) return;
  if (!dsc->rect_dsc) return;

  uint32_t idx = dsc->id;

  bool is_danger = false;

  if (chart == ui_voltageChart && idx < 31) {
    lv_coord_t val = history_voltage[idx];
    is_danger = (val > 0 && (val < UI_VOLTAGE_WARN_LOW || val > UI_VOLTAGE_WARN_HIGH));
  } else if (chart == ui_wattsChart && idx < 31) {
    lv_coord_t val = history_watts[idx];
    is_danger = (val > UI_WATTS_WARN_HIGH);
  }

  if (is_danger) {
    dsc->rect_dsc->bg_color = UI_CHART_DANGER_COLOR;
  }
}

void ui_chart_pressed_event_cb(lv_event_t *e) {
  if (history_mutex == NULL || xSemaphoreTake(history_mutex, pdMS_TO_TICKS(50)) != pdTRUE) return;

  lv_obj_t *chart = lv_event_get_target(e);
  uint32_t id = lv_chart_get_pressed_point(chart);
  if (id == LV_CHART_POINT_NONE) {
    xSemaphoreGive(history_mutex);
    restore_chart_defaults(lv_scr_act());
    return;
  }

  // Comprobar si la barra tiene datos
  bool has_data = false;
  if (chart == ui_voltageChart && id < 31) {
    has_data = (history_voltage[id] > 0);
  } else if (chart == ui_wattsChart && id < 31) {
    has_data = (history_watts[id] > 0);
  }

  if (!has_data) {
    // Barra vacía: mostrar "Sin datos"
    if (chart == ui_voltageChart) {
      if (ui_voltageVal) lv_label_set_text(ui_voltageVal, "0");
      if (ui_PotenciaLabel17) lv_label_set_text(ui_PotenciaLabel17, "Sin datos");
    } else if (chart == ui_wattsChart) {
      if (ui_wattsVal) lv_label_set_text(ui_wattsVal, "0.00");
      if (ui_PotenciaLabel16) lv_label_set_text(ui_PotenciaLabel16, "Sin datos");
    }
    xSemaphoreGive(history_mutex);
    return;
  }

  char formatted_time[32];
  format_timestamp(history_timestamps[id], formatted_time, sizeof(formatted_time));

  if (chart == ui_voltageChart && id < 31) {
    if (ui_voltageVal) {
      lv_label_set_text_fmt(ui_voltageVal, "%d", (int)history_voltage[id]);
      lv_obj_set_style_text_color(ui_voltageVal, UI_COLOR_ACCENT,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if (ui_PotenciaLabel17) {
      lv_label_set_text(ui_PotenciaLabel17, formatted_time);
    }
  } else if (chart == ui_wattsChart && id < 31) {
    if (ui_wattsVal) {
      lv_label_set_text_fmt(ui_wattsVal, "%.2f", (float)history_watts[id] / 100.0f);
      lv_obj_set_style_text_color(ui_wattsVal, UI_COLOR_ACCENT,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    if (ui_PotenciaLabel16) {
      lv_label_set_text(ui_PotenciaLabel16, formatted_time);
    }
  }
  xSemaphoreGive(history_mutex);
}

