// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void voltageStatsChange(lv_event_t *e) {
  _ui_screen_change(&ui_statsWatts, UI_ANIM_SWIPE_UP, UI_ANIM_SWIPE_DURATION,
                    UI_ANIM_SWIPE_DELAY, &ui_statsWatts_screen_init);
}

void statsWattsChange(lv_event_t *e) {
  _ui_screen_change(&ui_voltageStats, UI_ANIM_SWIPE_UP, UI_ANIM_SWIPE_DURATION,
                    UI_ANIM_SWIPE_DELAY, &ui_voltageStats_screen_init);
}

// ================================================================
// CONFIG: Callbacks reales (conectados a hardware vía main.cpp)
// ================================================================

// Funciones de hardware declaradas en main.cpp con C-linkage
extern void hw_set_brightness(uint8_t val);
extern void hw_wifi_toggle(bool enable);
extern void hw_restart(void);

void onBrightnessChange(int32_t value) {
  // Clamp a uint8_t
  uint8_t brightness = (uint8_t)(value > 255 ? 255 : (value < 0 ? 0 : value));
  hw_set_brightness(brightness);
}

void onWifiConfirm(bool enable) { hw_wifi_toggle(enable); }

void onRestartConfirm(void) { hw_restart(); }
