// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void voltageStatsChange(lv_event_t *e);
void statsWattsChange(lv_event_t *e);

// Config screen callbacks (llamados tras confirmar modal)
void onWifiConfirm(bool enable);
void onRestartConfirm(void);
void onBrightnessChange(int32_t value);
void onTurnOffScreen(void);
void ui_event_stats_toggle(lv_obj_t * label, lv_obj_t * chart);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
