// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_VOLTAJE 0
#define UI_THEME_COLOR_CORRIENTE 1
#define UI_THEME_COLOR_POTENCIA 2
#define UI_THEME_COLOR_STATS 3
#define UI_THEME_COLOR_VOLTAGE_RED 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_TEXTO 1

#define UI_THEME_FUNCIONALES 2

extern const ui_theme_variable_t _ui_theme_color_Voltaje[3];
extern const ui_theme_variable_t _ui_theme_alpha_Voltaje[3];

extern const ui_theme_variable_t _ui_theme_color_Corriente[3];
extern const ui_theme_variable_t _ui_theme_alpha_Corriente[3];

extern const ui_theme_variable_t _ui_theme_color_Potencia[3];
extern const ui_theme_variable_t _ui_theme_alpha_Potencia[3];

extern const ui_theme_variable_t _ui_theme_color_Stats[3];
extern const ui_theme_variable_t _ui_theme_alpha_Stats[3];

extern const ui_theme_variable_t _ui_theme_color_Voltage_Red[3];
extern const ui_theme_variable_t _ui_theme_alpha_Voltage_Red[3];

extern const uint32_t * ui_theme_colors[3];
extern const uint8_t * ui_theme_alphas[3];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
