// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT navPanel

static void nav_panel_screen_load_cb(lv_event_t * e)
{
    lv_obj_t * cui_navPanel = lv_event_get_user_data(e);
    lv_obj_t * circle4 = ui_comp_get_child(cui_navPanel, UI_COMP_NAVPANEL_CIRCLE4);
    lv_obj_t * circle5 = ui_comp_get_child(cui_navPanel, UI_COMP_NAVPANEL_CIRCLE5);

    if(is_wifi_enabled) {
        lv_obj_clear_flag(circle4, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(circle5, LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_add_flag(circle4, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(circle5, LV_OBJ_FLAG_HIDDEN);
    }
}

lv_obj_t * ui_navPanel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_navPanel;
    cui_navPanel = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_navPanel, LV_SIZE_CONTENT);
    lv_obj_set_height(cui_navPanel, LV_SIZE_CONTENT);
    lv_obj_set_x(cui_navPanel, 0);
    lv_obj_set_y(cui_navPanel, 100);
    lv_obj_set_align(cui_navPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_navPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_navPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(cui_navPanel, LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(cui_navPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    // Fondo negro justo al tamaño del contenido con borde redondeado
    lv_obj_set_style_bg_color(cui_navPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_navPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_navPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(cui_navPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(cui_navPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_navPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_circle1;
    cui_circle1 = lv_obj_create(cui_navPanel);
    lv_obj_set_width(cui_circle1, 10);
    lv_obj_set_height(cui_circle1, 10);
    lv_obj_set_align(cui_circle1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_circle1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(cui_circle1, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_circle1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_circle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_circle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_circle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_circle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_circle1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_circle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(cui_circle1, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(cui_circle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_4);
    lv_obj_set_style_bg_opa(cui_circle1, 255, LV_PART_MAIN | LV_STATE_USER_4);

    lv_obj_t * cui_circle2;
    cui_circle2 = lv_obj_create(cui_navPanel);
    lv_obj_set_width(cui_circle2, 10);
    lv_obj_set_height(cui_circle2, 10);
    lv_obj_set_align(cui_circle2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_circle2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(cui_circle2, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_circle2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_circle2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_circle2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_circle2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_circle2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_circle2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_circle2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(cui_circle2, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(cui_circle2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_4);
    lv_obj_set_style_bg_opa(cui_circle2, 255, LV_PART_MAIN | LV_STATE_USER_4);

    lv_obj_t * cui_circle3;
    cui_circle3 = lv_obj_create(cui_navPanel);
    lv_obj_set_width(cui_circle3, 10);
    lv_obj_set_height(cui_circle3, 10);
    lv_obj_set_align(cui_circle3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_circle3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(cui_circle3, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_circle3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_circle3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_circle3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_circle3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_circle3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_circle3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_circle3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(cui_circle3, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(cui_circle3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_4);
    lv_obj_set_style_bg_opa(cui_circle3, 255, LV_PART_MAIN | LV_STATE_USER_4);

    lv_obj_t * cui_circle4;
    cui_circle4 = lv_obj_create(cui_navPanel);
    lv_obj_set_width(cui_circle4, 10);
    lv_obj_set_height(cui_circle4, 10);
    lv_obj_set_align(cui_circle4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_circle4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(cui_circle4, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_circle4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_circle4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_circle4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_circle4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_circle4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_circle4, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_circle4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(cui_circle4, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(cui_circle4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_4);
    lv_obj_set_style_bg_opa(cui_circle4, 255, LV_PART_MAIN | LV_STATE_USER_4);

    lv_obj_t * cui_circle5;
    cui_circle5 = lv_obj_create(cui_navPanel);
    lv_obj_set_width(cui_circle5, 10);
    lv_obj_set_height(cui_circle5, 10);
    lv_obj_set_align(cui_circle5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_circle5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(cui_circle5, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_circle5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_circle5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_circle5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_circle5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_circle5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_circle5, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_circle5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(cui_circle5, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(cui_circle5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_4);
    lv_obj_set_style_bg_opa(cui_circle5, 255, LV_PART_MAIN | LV_STATE_USER_4);

    lv_obj_t * cui_circle6;
    cui_circle6 = lv_obj_create(cui_navPanel);
    lv_obj_set_width(cui_circle6, 10);
    lv_obj_set_height(cui_circle6, 10);
    lv_obj_set_align(cui_circle6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_circle6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(cui_circle6, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_circle6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_circle6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_circle6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_circle6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_circle6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_circle6, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_circle6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(cui_circle6, 255, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_color(cui_circle6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_4);
    lv_obj_set_style_bg_opa(cui_circle6, 255, LV_PART_MAIN | LV_STATE_USER_4);

    if (!is_wifi_enabled) {
        lv_obj_add_flag(cui_circle4, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(cui_circle5, LV_OBJ_FLAG_HIDDEN);
    }

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_NAVPANEL_NUM);
    children[UI_COMP_NAVPANEL_NAVPANEL] = cui_navPanel;
    children[UI_COMP_NAVPANEL_CIRCLE1] = cui_circle1;
    children[UI_COMP_NAVPANEL_CIRCLE2] = cui_circle2;
    children[UI_COMP_NAVPANEL_CIRCLE3] = cui_circle3;
    children[UI_COMP_NAVPANEL_CIRCLE4] = cui_circle4;
    children[UI_COMP_NAVPANEL_CIRCLE5] = cui_circle5;
    children[UI_COMP_NAVPANEL_CIRCLE6] = cui_circle6;
    lv_obj_add_event_cb(cui_navPanel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_navPanel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    
    // Al cargar la pantalla vinculada, refrescar visibilidad de puntos 4 y 5
    lv_obj_add_event_cb(comp_parent, nav_panel_screen_load_cb, LV_EVENT_SCREEN_LOAD_START, cui_navPanel);
    lv_obj_add_event_cb(comp_parent, nav_panel_screen_load_cb, LV_EVENT_SCREEN_LOADED, cui_navPanel);
    
    ui_comp_navPanel_create_hook(cui_navPanel);
    return cui_navPanel;
}

