// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_NAVPANEL_H
#define _UI_COMP_NAVPANEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT navPanel
#define UI_COMP_NAVPANEL_NAVPANEL 0
#define UI_COMP_NAVPANEL_CIRCLE1 1
#define UI_COMP_NAVPANEL_CIRCLE2 2
#define UI_COMP_NAVPANEL_CIRCLE3 3
#define UI_COMP_NAVPANEL_CIRCLE4 4
#define UI_COMP_NAVPANEL_CIRCLE5 5
#define UI_COMP_NAVPANEL_CIRCLE6 6
#define _UI_COMP_NAVPANEL_NUM 7
lv_obj_t * ui_navPanel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
