// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CORRIENTE_H
#define UI_CORRIENTE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_corriente
extern void ui_corriente_screen_init(void);
extern void ui_corriente_screen_destroy(void);
extern void ui_event_corriente(lv_event_t * e);
extern lv_obj_t * ui_corriente;
extern lv_obj_t * ui_contentPanel2;
extern lv_obj_t * ui_valoresPanel1;
extern lv_obj_t * ui_corrienteVal;
extern lv_obj_t * ui_voltageLabel1;
extern lv_obj_t * ui_extrasPanel1;
extern lv_obj_t * ui_secundario1Panel1;
extern lv_obj_t * ui_frecuenciaLabel2;
extern lv_obj_t * ui_pactivaVal;
extern lv_obj_t * ui_secundario2Panel1;
extern lv_obj_t * ui_frecuenciaLabel3;
extern lv_obj_t * ui_preactivaVal;
extern lv_obj_t * ui_navPanel1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

