// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_diagnostic = NULL;
lv_obj_t * ui_contentPanel9 = NULL;
lv_obj_t * ui_redPanel = NULL;
lv_obj_t * ui_redLabel = NULL;
lv_obj_t * ui_sectionPanel = NULL;
lv_obj_t * ui_ipPanel = NULL;
lv_obj_t * ui_elementLabel = NULL;
lv_obj_t * ui_elementSep = NULL;
lv_obj_t * ui_elementVal = NULL;
lv_obj_t * ui_rssiPanel = NULL;
lv_obj_t * ui_elementLabel1 = NULL;
lv_obj_t * ui_elementSep1 = NULL;
lv_obj_t * ui_elementVal1 = NULL;
lv_obj_t * ui_elementVal2 = NULL;
lv_obj_t * ui_rssiBar = NULL;
lv_obj_t * ui_uptimePanel = NULL;
lv_obj_t * ui_elementLabel2 = NULL;
lv_obj_t * ui_elementSep2 = NULL;
lv_obj_t * ui_elementVal3 = NULL;
lv_obj_t * ui_cloudPanel = NULL;
lv_obj_t * ui_cloudLabel = NULL;
lv_obj_t * ui_sectionPanel1 = NULL;
lv_obj_t * ui_mqttPanel = NULL;
lv_obj_t * ui_elementLabel3 = NULL;
lv_obj_t * ui_elementSep3 = NULL;
lv_obj_t * ui_elementVal4 = NULL;
lv_obj_t * ui_syncPanel = NULL;
lv_obj_t * ui_elementLabel5 = NULL;
lv_obj_t * ui_elementSep5 = NULL;
lv_obj_t * ui_elementVal7 = NULL;
lv_obj_t * ui_hardPanel = NULL;
lv_obj_t * ui_hardLabel = NULL;
lv_obj_t * ui_sectionPanel2 = NULL;
lv_obj_t * ui_macPanel = NULL;
lv_obj_t * ui_elementLabel4 = NULL;
lv_obj_t * ui_elementSep4 = NULL;
lv_obj_t * ui_elementVal5 = NULL;
lv_obj_t * ui_pzemPanel = NULL;
lv_obj_t * ui_elementLabel6 = NULL;
lv_obj_t * ui_elementSep6 = NULL;
lv_obj_t * ui_elementVal6 = NULL;
lv_obj_t * ui_heapPanel = NULL;
lv_obj_t * ui_elementLabel7 = NULL;
lv_obj_t * ui_elementSep7 = NULL;
lv_obj_t * ui_elementVal8 = NULL;
lv_obj_t * ui_navPanel7 = NULL;
// event funtions
void ui_event_diagnostic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_voltageStats, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_voltageStats_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_voltaje, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_voltaje_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_config, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_config_screen_init);
    }
}

// build funtions

void ui_diagnostic_screen_init(void)
{
    ui_diagnostic = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_diagnostic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_diagnostic, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_diagnostic, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_diagnostic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_diagnostic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_diagnostic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_diagnostic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_diagnostic, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_diagnostic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_diagnostic, &ui_font_Qualy24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contentPanel9 = lv_obj_create(ui_diagnostic);
    lv_obj_set_height(ui_contentPanel9, 237);
    lv_obj_set_width(ui_contentPanel9, lv_pct(100));
    lv_obj_set_x(ui_contentPanel9, 703);
    lv_obj_set_y(ui_contentPanel9, -188);
    lv_obj_set_flex_flow(ui_contentPanel9, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_contentPanel9, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_contentPanel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contentPanel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contentPanel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_contentPanel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_contentPanel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_contentPanel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_contentPanel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_redPanel = lv_obj_create(ui_contentPanel9);
    lv_obj_set_width(ui_redPanel, 285);
    lv_obj_set_flex_grow(ui_redPanel, 1);
    lv_obj_set_x(ui_redPanel, 703);
    lv_obj_set_y(ui_redPanel, -188);
    lv_obj_set_align(ui_redPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_redPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_redPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_redPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_redPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_redPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_redPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_redPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_redPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_redPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_redLabel = lv_label_create(ui_redPanel);
    lv_obj_set_height(ui_redLabel, 20);
    lv_obj_set_flex_grow(ui_redLabel, 1);
    lv_obj_set_align(ui_redLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_redLabel, "RED");
    lv_obj_set_style_text_color(ui_redLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_redLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_redLabel, &ui_font_Qualy24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sectionPanel = lv_obj_create(ui_redPanel);
    lv_obj_set_height(ui_sectionPanel, 68);
    lv_obj_set_flex_grow(ui_sectionPanel, 1);
    lv_obj_set_x(ui_sectionPanel, 703);
    lv_obj_set_y(ui_sectionPanel, -188);
    lv_obj_set_flex_flow(ui_sectionPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_sectionPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_add_flag(ui_sectionPanel, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_sectionPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sectionPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sectionPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sectionPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sectionPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_sectionPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_sectionPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_sectionPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_sectionPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_sectionPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_sectionPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_sectionPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_sectionPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_ipPanel = lv_obj_create(ui_sectionPanel);
    lv_obj_set_height(ui_ipPanel, 25);
    lv_obj_set_flex_grow(ui_ipPanel, 1);
    lv_obj_set_x(ui_ipPanel, 703);
    lv_obj_set_y(ui_ipPanel, -188);
    lv_obj_set_flex_flow(ui_ipPanel, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_ipPanel, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_ipPanel, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_ipPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ipPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ipPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ipPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ipPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ipPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ipPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementLabel = lv_label_create(ui_ipPanel);
    lv_obj_set_width(ui_elementLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_elementLabel, "IP Local");
    lv_obj_set_style_text_color(ui_elementLabel, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementLabel, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementSep = lv_label_create(ui_ipPanel);
    lv_obj_set_width(ui_elementSep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementSep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementSep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementSep, ":");
    lv_obj_add_flag(ui_elementSep, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementSep, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementSep, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementSep, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementVal = lv_label_create(ui_ipPanel);
    lv_obj_set_width(ui_elementVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementVal, "---.---.-.-");
    lv_obj_add_flag(ui_elementVal, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementVal, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementVal, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rssiPanel = lv_obj_create(ui_sectionPanel);
    lv_obj_set_height(ui_rssiPanel, 25);
    lv_obj_set_flex_grow(ui_rssiPanel, 1);
    lv_obj_set_x(ui_rssiPanel, 703);
    lv_obj_set_y(ui_rssiPanel, -188);
    lv_obj_set_flex_flow(ui_rssiPanel, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_rssiPanel, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_rssiPanel, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_rssiPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rssiPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rssiPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rssiPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rssiPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_rssiPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_rssiPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementLabel1 = lv_label_create(ui_rssiPanel);
    lv_obj_set_width(ui_elementLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementLabel1, "RSSI");
    lv_obj_set_style_text_color(ui_elementLabel1, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementLabel1, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementSep1 = lv_label_create(ui_rssiPanel);
    lv_obj_set_width(ui_elementSep1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementSep1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementSep1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementSep1, ":");
    lv_obj_add_flag(ui_elementSep1, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementSep1, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementSep1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementSep1, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementVal1 = lv_label_create(ui_rssiPanel);
    lv_obj_set_width(ui_elementVal1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementVal1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementVal1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementVal1, "--");
    lv_obj_add_flag(ui_elementVal1, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementVal1, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementVal1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementVal1, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementVal2 = lv_label_create(ui_rssiPanel);
    lv_obj_set_width(ui_elementVal2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementVal2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementVal2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementVal2, "dBm");
    lv_obj_add_flag(ui_elementVal2, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementVal2, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementVal2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementVal2, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rssiBar = lv_bar_create(ui_rssiPanel);
    lv_bar_set_value(ui_rssiBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_rssiBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_rssiBar, 150);
    lv_obj_set_height(ui_rssiBar, 10);
    lv_obj_set_align(ui_rssiBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rssiBar, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags

    ui_uptimePanel = lv_obj_create(ui_sectionPanel);
    lv_obj_set_height(ui_uptimePanel, 25);
    lv_obj_set_flex_grow(ui_uptimePanel, 1);
    lv_obj_set_x(ui_uptimePanel, 703);
    lv_obj_set_y(ui_uptimePanel, -188);
    lv_obj_set_flex_flow(ui_uptimePanel, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_uptimePanel, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_uptimePanel, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_uptimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_uptimePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uptimePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_uptimePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_uptimePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_uptimePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_uptimePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementLabel2 = lv_label_create(ui_uptimePanel);
    lv_obj_set_width(ui_elementLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementLabel2, "Uptime");
    lv_obj_set_style_text_color(ui_elementLabel2, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementLabel2, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementSep2 = lv_label_create(ui_uptimePanel);
    lv_obj_set_width(ui_elementSep2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementSep2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementSep2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementSep2, ":");
    lv_obj_add_flag(ui_elementSep2, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementSep2, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementSep2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementSep2, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementVal3 = lv_label_create(ui_uptimePanel);
    lv_obj_set_width(ui_elementVal3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementVal3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementVal3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementVal3, "---------");
    lv_obj_add_flag(ui_elementVal3, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementVal3, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementVal3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementVal3, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cloudPanel = lv_obj_create(ui_contentPanel9);
    lv_obj_set_width(ui_cloudPanel, 285);
    lv_obj_set_flex_grow(ui_cloudPanel, 1);
    lv_obj_set_x(ui_cloudPanel, 703);
    lv_obj_set_y(ui_cloudPanel, -188);
    lv_obj_set_align(ui_cloudPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cloudPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_cloudPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_cloudPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cloudPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cloudPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cloudPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cloudPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_cloudPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_cloudPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cloudLabel = lv_label_create(ui_cloudPanel);
    lv_obj_set_height(ui_cloudLabel, 20);
    lv_obj_set_flex_grow(ui_cloudLabel, 1);
    lv_obj_set_align(ui_cloudLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cloudLabel, "CLOUD");
    lv_obj_set_style_text_color(ui_cloudLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cloudLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cloudLabel, &ui_font_Qualy24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sectionPanel1 = lv_obj_create(ui_cloudPanel);
    lv_obj_set_height(ui_sectionPanel1, 68);
    lv_obj_set_flex_grow(ui_sectionPanel1, 1);
    lv_obj_set_x(ui_sectionPanel1, 703);
    lv_obj_set_y(ui_sectionPanel1, -188);
    lv_obj_set_flex_flow(ui_sectionPanel1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_sectionPanel1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_add_flag(ui_sectionPanel1, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_sectionPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sectionPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sectionPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sectionPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sectionPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_sectionPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_sectionPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_sectionPanel1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_sectionPanel1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_sectionPanel1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_sectionPanel1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_sectionPanel1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_sectionPanel1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_mqttPanel = lv_obj_create(ui_sectionPanel1);
    lv_obj_set_height(ui_mqttPanel, 25);
    lv_obj_set_flex_grow(ui_mqttPanel, 1);
    lv_obj_set_x(ui_mqttPanel, 703);
    lv_obj_set_y(ui_mqttPanel, -188);
    lv_obj_set_flex_flow(ui_mqttPanel, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_mqttPanel, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_mqttPanel, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_mqttPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mqttPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mqttPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mqttPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mqttPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_mqttPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_mqttPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementLabel3 = lv_label_create(ui_mqttPanel);
    lv_obj_set_width(ui_elementLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementLabel3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_elementLabel3, "MQTT Broker");
    lv_obj_set_style_text_color(ui_elementLabel3, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementLabel3, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementSep3 = lv_label_create(ui_mqttPanel);
    lv_obj_set_width(ui_elementSep3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementSep3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementSep3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementSep3, ":");
    lv_obj_add_flag(ui_elementSep3, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementSep3, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementSep3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementSep3, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementVal4 = lv_label_create(ui_mqttPanel);
    lv_obj_set_width(ui_elementVal4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementVal4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementVal4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementVal4, "-----");
    lv_obj_add_flag(ui_elementVal4, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementVal4, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementVal4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementVal4, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_syncPanel = lv_obj_create(ui_sectionPanel1);
    lv_obj_set_height(ui_syncPanel, 25);
    lv_obj_set_flex_grow(ui_syncPanel, 1);
    lv_obj_set_x(ui_syncPanel, 703);
    lv_obj_set_y(ui_syncPanel, -188);
    lv_obj_set_flex_flow(ui_syncPanel, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_syncPanel, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_syncPanel, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_syncPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_syncPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_syncPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_syncPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_syncPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_syncPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_syncPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementLabel5 = lv_label_create(ui_syncPanel);
    lv_obj_set_width(ui_elementLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementLabel5, "Last Sync");
    lv_obj_set_style_text_color(ui_elementLabel5, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementLabel5, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementSep5 = lv_label_create(ui_syncPanel);
    lv_obj_set_width(ui_elementSep5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementSep5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementSep5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementSep5, ":");
    lv_obj_add_flag(ui_elementSep5, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementSep5, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementSep5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementSep5, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementVal7 = lv_label_create(ui_syncPanel);
    lv_obj_set_width(ui_elementVal7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementVal7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementVal7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementVal7, "---------");
    lv_obj_add_flag(ui_elementVal7, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementVal7, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementVal7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementVal7, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hardPanel = lv_obj_create(ui_contentPanel9);
    lv_obj_set_width(ui_hardPanel, 277);
    lv_obj_set_flex_grow(ui_hardPanel, 1);
    lv_obj_set_x(ui_hardPanel, 703);
    lv_obj_set_y(ui_hardPanel, -188);
    lv_obj_set_align(ui_hardPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_hardPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_hardPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_add_flag(ui_hardPanel, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_hardPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_hardPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hardPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_hardPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_hardPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_hardPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_hardPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hardLabel = lv_label_create(ui_hardPanel);
    lv_obj_set_height(ui_hardLabel, 20);
    lv_obj_set_flex_grow(ui_hardLabel, 1);
    lv_obj_set_align(ui_hardLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hardLabel, "HARDWARE");
    lv_obj_set_style_text_color(ui_hardLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hardLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hardLabel, &ui_font_Qualy24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sectionPanel2 = lv_obj_create(ui_hardPanel);
    lv_obj_set_height(ui_sectionPanel2, 68);
    lv_obj_set_flex_grow(ui_sectionPanel2, 1);
    lv_obj_set_x(ui_sectionPanel2, 703);
    lv_obj_set_y(ui_sectionPanel2, -188);
    lv_obj_set_flex_flow(ui_sectionPanel2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_sectionPanel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_add_flag(ui_sectionPanel2, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_sectionPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sectionPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sectionPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_sectionPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sectionPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_sectionPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_sectionPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_sectionPanel2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_sectionPanel2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_sectionPanel2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_sectionPanel2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_sectionPanel2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_sectionPanel2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_macPanel = lv_obj_create(ui_sectionPanel2);
    lv_obj_set_height(ui_macPanel, 25);
    lv_obj_set_flex_grow(ui_macPanel, 1);
    lv_obj_set_x(ui_macPanel, 703);
    lv_obj_set_y(ui_macPanel, -188);
    lv_obj_set_flex_flow(ui_macPanel, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_macPanel, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_macPanel, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_macPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_macPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_macPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_macPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_macPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_macPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_macPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementLabel4 = lv_label_create(ui_macPanel);
    lv_obj_set_width(ui_elementLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementLabel4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_elementLabel4, "MAC Address");
    lv_obj_set_style_text_color(ui_elementLabel4, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementLabel4, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementSep4 = lv_label_create(ui_macPanel);
    lv_obj_set_width(ui_elementSep4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementSep4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementSep4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementSep4, ":");
    lv_obj_add_flag(ui_elementSep4, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementSep4, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementSep4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementSep4, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementVal5 = lv_label_create(ui_macPanel);
    lv_obj_set_width(ui_elementVal5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementVal5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementVal5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementVal5, "-----------");
    lv_obj_add_flag(ui_elementVal5, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementVal5, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementVal5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementVal5, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pzemPanel = lv_obj_create(ui_sectionPanel2);
    lv_obj_set_height(ui_pzemPanel, 25);
    lv_obj_set_flex_grow(ui_pzemPanel, 1);
    lv_obj_set_x(ui_pzemPanel, 703);
    lv_obj_set_y(ui_pzemPanel, -188);
    lv_obj_set_flex_flow(ui_pzemPanel, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_pzemPanel, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_pzemPanel, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_pzemPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pzemPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pzemPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pzemPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pzemPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_pzemPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_pzemPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementLabel6 = lv_label_create(ui_pzemPanel);
    lv_obj_set_width(ui_elementLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementLabel6, "PZEM Status");
    lv_obj_set_style_text_color(ui_elementLabel6, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementLabel6, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementSep6 = lv_label_create(ui_pzemPanel);
    lv_obj_set_width(ui_elementSep6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementSep6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementSep6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementSep6, ":");
    lv_obj_add_flag(ui_elementSep6, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementSep6, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementSep6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementSep6, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementVal6 = lv_label_create(ui_pzemPanel);
    lv_obj_set_width(ui_elementVal6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementVal6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementVal6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementVal6, "-----------");
    lv_obj_add_flag(ui_elementVal6, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementVal6, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementVal6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementVal6, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heapPanel = lv_obj_create(ui_sectionPanel2);
    lv_obj_set_height(ui_heapPanel, 25);
    lv_obj_set_flex_grow(ui_heapPanel, 1);
    lv_obj_set_x(ui_heapPanel, 703);
    lv_obj_set_y(ui_heapPanel, -188);
    lv_obj_set_flex_flow(ui_heapPanel, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_heapPanel, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_heapPanel, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_clear_flag(ui_heapPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_heapPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_heapPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_heapPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_heapPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_heapPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_heapPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementLabel7 = lv_label_create(ui_heapPanel);
    lv_obj_set_width(ui_elementLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementLabel7, "Free Heap");
    lv_obj_set_style_text_color(ui_elementLabel7, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementLabel7, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementSep7 = lv_label_create(ui_heapPanel);
    lv_obj_set_width(ui_elementSep7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementSep7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementSep7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementSep7, ":");
    lv_obj_add_flag(ui_elementSep7, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementSep7, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementSep7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementSep7, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_elementVal8 = lv_label_create(ui_heapPanel);
    lv_obj_set_width(ui_elementVal8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_elementVal8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_elementVal8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_elementVal8, "------/-----");
    lv_obj_add_flag(ui_elementVal8, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_elementVal8, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_elementVal8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_elementVal8, &ui_font_Qualy14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navPanel7 = ui_navPanel_create(ui_diagnostic);
    lv_obj_set_x(ui_navPanel7, 0);
    lv_obj_set_y(ui_navPanel7, 101);

    lv_obj_set_style_bg_color(ui_comp_get_child(ui_navPanel7, UI_COMP_NAVPANEL_CIRCLE6), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_navPanel7, UI_COMP_NAVPANEL_CIRCLE6), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_diagnostic, ui_event_diagnostic, LV_EVENT_ALL, NULL);

}

void ui_diagnostic_screen_destroy(void)
{
    if(ui_diagnostic) lv_obj_del(ui_diagnostic);

    // NULL screen variables
    ui_diagnostic = NULL;
    ui_contentPanel9 = NULL;
    ui_redPanel = NULL;
    ui_redLabel = NULL;
    ui_sectionPanel = NULL;
    ui_ipPanel = NULL;
    ui_elementLabel = NULL;
    ui_elementSep = NULL;
    ui_elementVal = NULL;
    ui_rssiPanel = NULL;
    ui_elementLabel1 = NULL;
    ui_elementSep1 = NULL;
    ui_elementVal1 = NULL;
    ui_elementVal2 = NULL;
    ui_rssiBar = NULL;
    ui_uptimePanel = NULL;
    ui_elementLabel2 = NULL;
    ui_elementSep2 = NULL;
    ui_elementVal3 = NULL;
    ui_cloudPanel = NULL;
    ui_cloudLabel = NULL;
    ui_sectionPanel1 = NULL;
    ui_mqttPanel = NULL;
    ui_elementLabel3 = NULL;
    ui_elementSep3 = NULL;
    ui_elementVal4 = NULL;
    ui_syncPanel = NULL;
    ui_elementLabel5 = NULL;
    ui_elementSep5 = NULL;
    ui_elementVal7 = NULL;
    ui_hardPanel = NULL;
    ui_hardLabel = NULL;
    ui_sectionPanel2 = NULL;
    ui_macPanel = NULL;
    ui_elementLabel4 = NULL;
    ui_elementSep4 = NULL;
    ui_elementVal5 = NULL;
    ui_pzemPanel = NULL;
    ui_elementLabel6 = NULL;
    ui_elementSep6 = NULL;
    ui_elementVal6 = NULL;
    ui_heapPanel = NULL;
    ui_elementLabel7 = NULL;
    ui_elementSep7 = NULL;
    ui_elementVal8 = NULL;
    ui_navPanel7 = NULL;

}
