// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DIAGNOSTIC_H
#define UI_DIAGNOSTIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_diagnostic
extern void ui_diagnostic_screen_init(void);
extern void ui_diagnostic_screen_destroy(void);
extern void ui_event_diagnostic(lv_event_t * e);
extern lv_obj_t * ui_diagnostic;
extern lv_obj_t * ui_contentPanel9;
extern lv_obj_t * ui_redPanel;
extern lv_obj_t * ui_redLabel;
extern lv_obj_t * ui_sectionPanel;
extern lv_obj_t * ui_ipPanel;
extern lv_obj_t * ui_elementLabel;
extern lv_obj_t * ui_elementSep;
extern lv_obj_t * ui_elementVal;
extern lv_obj_t * ui_rssiPanel;
extern lv_obj_t * ui_elementLabel1;
extern lv_obj_t * ui_elementSep1;
extern lv_obj_t * ui_elementVal1;
extern lv_obj_t * ui_elementVal2;
extern lv_obj_t * ui_rssiBar;
extern lv_obj_t * ui_uptimePanel;
extern lv_obj_t * ui_elementLabel2;
extern lv_obj_t * ui_elementSep2;
extern lv_obj_t * ui_elementVal3;
extern lv_obj_t * ui_cloudPanel;
extern lv_obj_t * ui_cloudLabel;
extern lv_obj_t * ui_sectionPanel1;
extern lv_obj_t * ui_mqttPanel;
extern lv_obj_t * ui_elementLabel3;
extern lv_obj_t * ui_elementSep3;
extern lv_obj_t * ui_elementVal4;
extern lv_obj_t * ui_syncPanel;
extern lv_obj_t * ui_elementLabel5;
extern lv_obj_t * ui_elementSep5;
extern lv_obj_t * ui_elementVal7;
extern lv_obj_t * ui_hardPanel;
extern lv_obj_t * ui_hardLabel;
extern lv_obj_t * ui_sectionPanel2;
extern lv_obj_t * ui_macPanel;
extern lv_obj_t * ui_elementLabel4;
extern lv_obj_t * ui_elementSep4;
extern lv_obj_t * ui_elementVal5;
extern lv_obj_t * ui_pzemPanel;
extern lv_obj_t * ui_elementLabel6;
extern lv_obj_t * ui_elementSep6;
extern lv_obj_t * ui_elementVal6;
extern lv_obj_t * ui_heapPanel;
extern lv_obj_t * ui_elementLabel7;
extern lv_obj_t * ui_elementSep7;
extern lv_obj_t * ui_elementVal8;
extern lv_obj_t * ui_navPanel7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

