// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DASHBOARD_H
#define UI_DASHBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dashboard
extern void ui_dashboard_screen_init(void);
extern void ui_dashboard_screen_destroy(void);
extern void ui_event_dashboard(lv_event_t * e);
extern lv_obj_t * ui_dashboard;
extern lv_obj_t * ui_contentPanel3;
extern lv_obj_t * ui_valoresPanelVoltaje3;
extern lv_obj_t * ui_secundario1Panel6;
extern lv_obj_t * ui_VoltajeValD;
extern lv_obj_t * ui_PotenciaLabel3;
extern lv_obj_t * ui_secundario1Panel3;
extern lv_obj_t * ui_frecuenciaValD;
extern lv_obj_t * ui_DateVal5;
extern lv_obj_t * ui_valoresPanelVoltaje1;
extern lv_obj_t * ui_secundario1Panel2;
extern lv_obj_t * ui_CorrienteValD;
extern lv_obj_t * ui_PotenciaLabel1;
extern lv_obj_t * ui_secundario1Panel4;
extern lv_obj_t * ui_pactivaValD;
extern lv_obj_t * ui_DateVal6;
extern lv_obj_t * ui_valoresPanelVoltaje2;
extern lv_obj_t * ui_secundario1Panel5;
extern lv_obj_t * ui_PotenciaValD;
extern lv_obj_t * ui_PotenciaLabel2;
extern lv_obj_t * ui_secundario1Panel7;
extern lv_obj_t * ui_DateVal3;
extern lv_obj_t * ui_valoresPanelVoltaje4;
extern lv_obj_t * ui_secundario1Panel8;
extern lv_obj_t * ui_energiaValD;
extern lv_obj_t * ui_PotenciaLabel4;
extern lv_obj_t * ui_secundario1Panel9;
extern lv_obj_t * ui_tiempoLabel;
extern lv_obj_t * ui_navPanel2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_secundario1Panel6;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

