// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MODO_DIARIO_24HRS_H
#define UI_MODO_DIARIO_24HRS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Modo_Diario_24hrs
extern void ui_Modo_Diario_24hrs_screen_init(void);
extern void ui_Modo_Diario_24hrs_screen_destroy(void);
extern lv_obj_t * ui_Modo_Diario_24hrs;
extern lv_obj_t * ui_PotenciaLabel6;
extern lv_obj_t * ui_PotenciaLabel7;
extern lv_obj_t * ui_valoresPanel2;
extern lv_obj_t * ui_valoresPanel3;
extern lv_obj_t * ui_navPanel5;
extern lv_obj_t * ui_PotenciaLabel5;
extern lv_obj_t * ui_PotenciaLabel8;
extern lv_obj_t * ui_PotenciaLabel9;
extern lv_obj_t * ui_PotenciaLabel10;
extern lv_obj_t * ui_PotenciaLabel11;
extern lv_obj_t * ui_PotenciaLabel12;
extern lv_obj_t * ui_PotenciaLabel13;
extern lv_obj_t * ui_PotenciaLabel14;
extern lv_obj_t * ui_valoresPanel4;
extern lv_obj_t * ui_valoresPanel5;
extern lv_obj_t * ui_valoresPanel6;
extern lv_obj_t * ui_valoresPanel7;
extern lv_obj_t * ui_valoresPanel8;
extern lv_obj_t * ui_valoresPanel9;
extern lv_obj_t * ui_valoresPanel10;
extern lv_obj_t * ui_valoresPanel11;
extern lv_obj_t * ui_valoresPanel12;
extern lv_obj_t * ui_valoresPanel13;
extern lv_obj_t * ui_valoresPanel14;
extern lv_obj_t * ui_PotenciaLabel15;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

