// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Modo_Diario_24hrs = NULL;
lv_obj_t * ui_PotenciaLabel6 = NULL;
lv_obj_t * ui_PotenciaLabel7 = NULL;
lv_obj_t * ui_valoresPanel2 = NULL;
lv_obj_t * ui_valoresPanel3 = NULL;
lv_obj_t * ui_navPanel5 = NULL;
lv_obj_t * ui_PotenciaLabel5 = NULL;
lv_obj_t * ui_PotenciaLabel8 = NULL;
lv_obj_t * ui_PotenciaLabel9 = NULL;
lv_obj_t * ui_PotenciaLabel10 = NULL;
lv_obj_t * ui_PotenciaLabel11 = NULL;
lv_obj_t * ui_PotenciaLabel12 = NULL;
lv_obj_t * ui_PotenciaLabel13 = NULL;
lv_obj_t * ui_PotenciaLabel14 = NULL;
lv_obj_t * ui_valoresPanel4 = NULL;
lv_obj_t * ui_valoresPanel5 = NULL;
lv_obj_t * ui_valoresPanel6 = NULL;
lv_obj_t * ui_valoresPanel7 = NULL;
lv_obj_t * ui_valoresPanel8 = NULL;
lv_obj_t * ui_valoresPanel9 = NULL;
lv_obj_t * ui_valoresPanel10 = NULL;
lv_obj_t * ui_valoresPanel11 = NULL;
lv_obj_t * ui_valoresPanel12 = NULL;
lv_obj_t * ui_valoresPanel13 = NULL;
lv_obj_t * ui_valoresPanel14 = NULL;
lv_obj_t * ui_PotenciaLabel15 = NULL;
// event funtions

// build funtions

void ui_Modo_Diario_24hrs_screen_init(void)
{
    ui_Modo_Diario_24hrs = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Modo_Diario_24hrs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Modo_Diario_24hrs, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Modo_Diario_24hrs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PotenciaLabel6 = lv_label_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_PotenciaLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotenciaLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PotenciaLabel6, -88);
    lv_obj_set_y(ui_PotenciaLabel6, -103);
    lv_obj_set_align(ui_PotenciaLabel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PotenciaLabel6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PotenciaLabel6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PotenciaLabel6, "Consumo diario (24) horas");
    lv_obj_set_style_text_color(ui_PotenciaLabel6, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PotenciaLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PotenciaLabel6, &ui_font_Unidades, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PotenciaLabel7 = lv_label_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_PotenciaLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotenciaLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PotenciaLabel7, 218);
    lv_obj_set_y(ui_PotenciaLabel7, -102);
    lv_obj_set_align(ui_PotenciaLabel7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PotenciaLabel7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PotenciaLabel7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PotenciaLabel7, "▲ 650W");
    lv_obj_set_style_text_color(ui_PotenciaLabel7, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PotenciaLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PotenciaLabel7, &ui_font_Unidades, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valoresPanel2 = lv_obj_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_valoresPanel2, 479);
    lv_obj_set_height(ui_valoresPanel2, 8);
    lv_obj_set_x(ui_valoresPanel2, 1);
    lv_obj_set_y(ui_valoresPanel2, 20);
    lv_obj_set_align(ui_valoresPanel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valoresPanel2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_valoresPanel2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_valoresPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_valoresPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_valoresPanel2, lv_color_hex(0xB388FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valoresPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_valoresPanel2, lv_color_hex(0xB388FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_valoresPanel2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_valoresPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_valoresPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_valoresPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_valoresPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_valoresPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valoresPanel3 = lv_obj_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_valoresPanel3, 407);
    lv_obj_set_height(ui_valoresPanel3, 91);
    lv_obj_set_x(ui_valoresPanel3, 6);
    lv_obj_set_y(ui_valoresPanel3, -22);
    lv_obj_set_align(ui_valoresPanel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valoresPanel3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_valoresPanel3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_valoresPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_valoresPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_valoresPanel3, lv_color_hex(0xB388FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valoresPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_valoresPanel3, lv_color_hex(0xB388FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_valoresPanel3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_valoresPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_navPanel5 = ui_navPanel_create(ui_Modo_Diario_24hrs);
    lv_obj_set_x(ui_navPanel5, 0);
    lv_obj_set_y(ui_navPanel5, 101);

    lv_obj_set_style_bg_color(ui_comp_get_child(ui_navPanel5, UI_COMP_NAVPANEL_CIRCLE4), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_navPanel5, UI_COMP_NAVPANEL_CIRCLE4), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PotenciaLabel5 = lv_label_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_PotenciaLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotenciaLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PotenciaLabel5, -194);
    lv_obj_set_y(ui_PotenciaLabel5, 37);
    lv_obj_set_align(ui_PotenciaLabel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PotenciaLabel5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PotenciaLabel5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PotenciaLabel5, "0");
    lv_obj_set_style_text_color(ui_PotenciaLabel5, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PotenciaLabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PotenciaLabel5, &ui_font_Unidades, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PotenciaLabel8 = lv_label_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_PotenciaLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotenciaLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PotenciaLabel8, -142);
    lv_obj_set_y(ui_PotenciaLabel8, 37);
    lv_obj_set_align(ui_PotenciaLabel8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PotenciaLabel8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PotenciaLabel8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PotenciaLabel8, "4");
    lv_obj_set_style_text_color(ui_PotenciaLabel8, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PotenciaLabel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PotenciaLabel8, &ui_font_Unidades, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PotenciaLabel9 = lv_label_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_PotenciaLabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotenciaLabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PotenciaLabel9, -76);
    lv_obj_set_y(ui_PotenciaLabel9, 37);
    lv_obj_set_align(ui_PotenciaLabel9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PotenciaLabel9, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PotenciaLabel9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PotenciaLabel9, "8");
    lv_obj_set_style_text_color(ui_PotenciaLabel9, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PotenciaLabel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PotenciaLabel9, &ui_font_Unidades, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PotenciaLabel10 = lv_label_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_PotenciaLabel10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotenciaLabel10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PotenciaLabel10, 2);
    lv_obj_set_y(ui_PotenciaLabel10, 35);
    lv_obj_set_align(ui_PotenciaLabel10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PotenciaLabel10, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PotenciaLabel10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PotenciaLabel10, "12");
    lv_obj_set_style_text_color(ui_PotenciaLabel10, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PotenciaLabel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PotenciaLabel10, &ui_font_Unidades, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PotenciaLabel11 = lv_label_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_PotenciaLabel11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotenciaLabel11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PotenciaLabel11, 210);
    lv_obj_set_y(ui_PotenciaLabel11, 36);
    lv_obj_set_align(ui_PotenciaLabel11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PotenciaLabel11, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PotenciaLabel11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PotenciaLabel11, "24");
    lv_obj_set_style_text_color(ui_PotenciaLabel11, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PotenciaLabel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PotenciaLabel11, &ui_font_Unidades, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PotenciaLabel12 = lv_label_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_PotenciaLabel12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotenciaLabel12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PotenciaLabel12, 71);
    lv_obj_set_y(ui_PotenciaLabel12, 37);
    lv_obj_set_align(ui_PotenciaLabel12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PotenciaLabel12, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PotenciaLabel12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PotenciaLabel12, "16");
    lv_obj_set_style_text_color(ui_PotenciaLabel12, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PotenciaLabel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PotenciaLabel12, &ui_font_Unidades, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PotenciaLabel13 = lv_label_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_PotenciaLabel13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotenciaLabel13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PotenciaLabel13, 142);
    lv_obj_set_y(ui_PotenciaLabel13, 37);
    lv_obj_set_align(ui_PotenciaLabel13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PotenciaLabel13, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PotenciaLabel13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PotenciaLabel13, "20");
    lv_obj_set_style_text_color(ui_PotenciaLabel13, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PotenciaLabel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PotenciaLabel13, &ui_font_Unidades, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PotenciaLabel14 = lv_label_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_PotenciaLabel14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotenciaLabel14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PotenciaLabel14, -210);
    lv_obj_set_y(ui_PotenciaLabel14, 94);
    lv_obj_set_align(ui_PotenciaLabel14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PotenciaLabel14, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PotenciaLabel14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PotenciaLabel14, "Desliza");
    lv_obj_set_style_text_color(ui_PotenciaLabel14, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PotenciaLabel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PotenciaLabel14, &ui_font_Micro_text, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valoresPanel4 = lv_obj_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_valoresPanel4, 17);
    lv_obj_set_height(ui_valoresPanel4, 54);
    lv_obj_set_x(ui_valoresPanel4, -189);
    lv_obj_set_y(ui_valoresPanel4, -40);
    lv_obj_set_align(ui_valoresPanel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valoresPanel4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_valoresPanel4, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_valoresPanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_valoresPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_valoresPanel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valoresPanel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_valoresPanel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_valoresPanel4, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_valoresPanel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_valoresPanel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valoresPanel5 = lv_obj_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_valoresPanel5, 17);
    lv_obj_set_height(ui_valoresPanel5, 39);
    lv_obj_set_x(ui_valoresPanel5, -174);
    lv_obj_set_y(ui_valoresPanel5, -48);
    lv_obj_set_align(ui_valoresPanel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valoresPanel5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_valoresPanel5, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_valoresPanel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_valoresPanel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_valoresPanel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valoresPanel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_valoresPanel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_valoresPanel5, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_valoresPanel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_valoresPanel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valoresPanel6 = lv_obj_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_valoresPanel6, 17);
    lv_obj_set_height(ui_valoresPanel6, 21);
    lv_obj_set_x(ui_valoresPanel6, -159);
    lv_obj_set_y(ui_valoresPanel6, -57);
    lv_obj_set_align(ui_valoresPanel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valoresPanel6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_valoresPanel6, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_valoresPanel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_valoresPanel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_valoresPanel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valoresPanel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_valoresPanel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_valoresPanel6, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_valoresPanel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_valoresPanel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valoresPanel7 = lv_obj_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_valoresPanel7, 17);
    lv_obj_set_height(ui_valoresPanel7, 8);
    lv_obj_set_x(ui_valoresPanel7, -144);
    lv_obj_set_y(ui_valoresPanel7, -63);
    lv_obj_set_align(ui_valoresPanel7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valoresPanel7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_valoresPanel7, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_valoresPanel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_valoresPanel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_valoresPanel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valoresPanel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_valoresPanel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_valoresPanel7, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_valoresPanel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_valoresPanel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valoresPanel8 = lv_obj_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_valoresPanel8, 17);
    lv_obj_set_height(ui_valoresPanel8, 98);
    lv_obj_set_x(ui_valoresPanel8, -105);
    lv_obj_set_y(ui_valoresPanel8, -26);
    lv_obj_set_align(ui_valoresPanel8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valoresPanel8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_valoresPanel8, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_valoresPanel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_valoresPanel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_valoresPanel8, lv_color_hex(0xFF3D00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valoresPanel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_valoresPanel8, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_valoresPanel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_valoresPanel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valoresPanel9 = lv_obj_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_valoresPanel9, 472);
    lv_obj_set_height(ui_valoresPanel9, 5);
    lv_obj_set_x(ui_valoresPanel9, 1);
    lv_obj_set_y(ui_valoresPanel9, -13);
    lv_obj_set_align(ui_valoresPanel9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valoresPanel9, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_valoresPanel9, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_valoresPanel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_valoresPanel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_valoresPanel9, lv_color_hex(0xFEEA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valoresPanel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_valoresPanel9, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_valoresPanel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_valoresPanel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valoresPanel10 = lv_obj_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_valoresPanel10, 17);
    lv_obj_set_height(ui_valoresPanel10, 54);
    lv_obj_set_x(ui_valoresPanel10, 201);
    lv_obj_set_y(ui_valoresPanel10, -40);
    lv_obj_set_align(ui_valoresPanel10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valoresPanel10, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_valoresPanel10, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_valoresPanel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_valoresPanel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_valoresPanel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valoresPanel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_valoresPanel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_valoresPanel10, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_valoresPanel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_valoresPanel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valoresPanel11 = lv_obj_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_valoresPanel11, 17);
    lv_obj_set_height(ui_valoresPanel11, 29);
    lv_obj_set_x(ui_valoresPanel11, 186);
    lv_obj_set_y(ui_valoresPanel11, -53);
    lv_obj_set_align(ui_valoresPanel11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valoresPanel11, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_valoresPanel11, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_valoresPanel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_valoresPanel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_valoresPanel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valoresPanel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_valoresPanel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_valoresPanel11, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_valoresPanel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_valoresPanel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valoresPanel12 = lv_obj_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_valoresPanel12, 17);
    lv_obj_set_height(ui_valoresPanel12, 29);
    lv_obj_set_x(ui_valoresPanel12, 171);
    lv_obj_set_y(ui_valoresPanel12, -53);
    lv_obj_set_align(ui_valoresPanel12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valoresPanel12, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_valoresPanel12, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_valoresPanel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_valoresPanel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_valoresPanel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valoresPanel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_valoresPanel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_valoresPanel12, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_valoresPanel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_valoresPanel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valoresPanel13 = lv_obj_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_valoresPanel13, 17);
    lv_obj_set_height(ui_valoresPanel13, 16);
    lv_obj_set_x(ui_valoresPanel13, 156);
    lv_obj_set_y(ui_valoresPanel13, -59);
    lv_obj_set_align(ui_valoresPanel13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valoresPanel13, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_valoresPanel13, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_valoresPanel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_valoresPanel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_valoresPanel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valoresPanel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_valoresPanel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_valoresPanel13, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_valoresPanel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_valoresPanel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_valoresPanel14 = lv_obj_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_valoresPanel14, 17);
    lv_obj_set_height(ui_valoresPanel14, 29);
    lv_obj_set_x(ui_valoresPanel14, 186);
    lv_obj_set_y(ui_valoresPanel14, -53);
    lv_obj_set_align(ui_valoresPanel14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_valoresPanel14, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_valoresPanel14, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_valoresPanel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_valoresPanel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_valoresPanel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_valoresPanel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_valoresPanel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_valoresPanel14, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_valoresPanel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_valoresPanel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PotenciaLabel15 = lv_label_create(ui_Modo_Diario_24hrs);
    lv_obj_set_width(ui_PotenciaLabel15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PotenciaLabel15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PotenciaLabel15, 200);
    lv_obj_set_y(ui_PotenciaLabel15, 92);
    lv_obj_set_align(ui_PotenciaLabel15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PotenciaLabel15, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PotenciaLabel15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_PotenciaLabel15, "	  Cambiar\nDiario/Mensual");
    lv_obj_set_style_text_color(ui_PotenciaLabel15, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PotenciaLabel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PotenciaLabel15, &ui_font_Micro_text, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Modo_Diario_24hrs_screen_destroy(void)
{
    if(ui_Modo_Diario_24hrs) lv_obj_del(ui_Modo_Diario_24hrs);

    // NULL screen variables
    ui_Modo_Diario_24hrs = NULL;
    ui_PotenciaLabel6 = NULL;
    ui_PotenciaLabel7 = NULL;
    ui_valoresPanel2 = NULL;
    ui_valoresPanel3 = NULL;
    ui_navPanel5 = NULL;
    ui_PotenciaLabel5 = NULL;
    ui_PotenciaLabel8 = NULL;
    ui_PotenciaLabel9 = NULL;
    ui_PotenciaLabel10 = NULL;
    ui_PotenciaLabel11 = NULL;
    ui_PotenciaLabel12 = NULL;
    ui_PotenciaLabel13 = NULL;
    ui_PotenciaLabel14 = NULL;
    ui_valoresPanel4 = NULL;
    ui_valoresPanel5 = NULL;
    ui_valoresPanel6 = NULL;
    ui_valoresPanel7 = NULL;
    ui_valoresPanel8 = NULL;
    ui_valoresPanel9 = NULL;
    ui_valoresPanel10 = NULL;
    ui_valoresPanel11 = NULL;
    ui_valoresPanel12 = NULL;
    ui_valoresPanel13 = NULL;
    ui_valoresPanel14 = NULL;
    ui_PotenciaLabel15 = NULL;

}
