// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_STATSWATTS_H
#define UI_STATSWATTS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_statsWatts
extern void ui_statsWatts_screen_init(void);
extern void ui_statsWatts_screen_destroy(void);
extern void ui_event_statsWatts(lv_event_t * e);
extern lv_obj_t * ui_statsWatts;
extern lv_obj_t * ui_contentPanel1;
extern lv_obj_t * ui_contentPanel4;
extern lv_obj_t * ui_PotenciaLabel16;
extern lv_obj_t * ui_contentPanel5;
extern lv_obj_t * ui_PotenciaLabel20;
extern lv_obj_t * ui_PotenciaLabel21;
extern lv_obj_t * ui_Chart;
extern lv_obj_t * ui_navPanel3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

