// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_VOLTAJE_H
#define UI_VOLTAJE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_voltaje
extern void ui_voltaje_screen_init(void);
extern void ui_voltaje_screen_destroy(void);
extern void ui_event_voltaje(lv_event_t * e);
extern lv_obj_t * ui_voltaje;
extern lv_obj_t * ui_contentPanel;
extern lv_obj_t * ui_valoresPanel;
extern lv_obj_t * ui_voltajeVal;
extern lv_obj_t * ui_voltageLabel;
extern lv_obj_t * ui_extrasPanel;
extern lv_obj_t * ui_secundario1Panel;
extern lv_obj_t * ui_frecuenciaLabel;
extern lv_obj_t * ui_frecuencia;
extern lv_obj_t * ui_secundario2Panel;
extern lv_obj_t * ui_potenciaLabel;
extern lv_obj_t * ui_potencia;
extern lv_obj_t * ui_navPanel4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Voltage;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

