// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_VOLTAGESTATS_H
#define UI_VOLTAGESTATS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_voltageStats
extern void ui_voltageStats_screen_init(void);
extern void ui_voltageStats_screen_destroy(void);
extern void ui_event_voltageStats(lv_event_t * e);
extern lv_obj_t * ui_voltageStats;
extern lv_obj_t * ui_contentPanel6;
extern lv_obj_t * ui_contentPanel7;
extern lv_obj_t * ui_PotenciaLabel17;
extern lv_obj_t * ui_contentPanel8;
extern lv_obj_t * ui_voltageVal;
extern lv_obj_t * ui_PotenciaLabel19;
extern lv_obj_t * ui_voltageChart;
extern lv_obj_t * ui_navPanel6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

